### ISSUE TITLE
Walkthough problem

### ISSUE THREAD

**Issue by feiranwang** [dennybritz/deepdive#65]
Got a problem on the 3rd step of the walkthrough: Creating a new DeepDive application. 

Messages:
[info] Loading project definition from /home/feiran/workspace/deepdive/project
[info] Set current project to deepdive (in build file:/home/feiran/workspace/deepdive/)
[info] Running org.deepdive.Main -c /home/feiran/workspace/deepdive/app/./application.conf
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/feiran/workspace/deepdive/lib/sampler-assembly-0.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/feiran/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.0.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
16:34:07.609 [][][Slf4jLogger] INFO  Slf4jLogger started
16:34:07.635 [run-main-0][EventStream(akka://deepdive)][EventStream] DEBUG logger log1-Slf4jLogger started
16:34:07.638 [run-main-0][EventStream(akka://deepdive)][EventStream] DEBUG Default Loggers started
16:34:07.655 [run-main-0][Main$(akka://deepdive)][Main$] INFO  Running pipeline with configuration from /home/feiran/workspace/deepdive/app/./application.conf
16:34:07.670 [run-main-0][SettingsParser$(akka://deepdive)][SettingsParser$] WARN  No schema defined.
16:34:07.693 [run-main-0][JdbcDataStore$(akka://deepdive)][JdbcDataStore$] INFO  Intializing all JDBC data stores
[error](run-main-0) scalikejdbc.config.ConfigurationException: Configuration error for database 'default. Map(poolInitialSize -> 16, connectionTimeoutMillis -> 1000, poolMaxSize -> 512)
scalikejdbc.config.ConfigurationException: Configuration error for database 'default. Map(poolInitialSize -> 16, connectionTimeoutMillis -> 1000, poolMaxSize -> 512)
    at scalikejdbc.config.TypesafeConfigReader$$anonfun$readJDBCSettings$2.apply(TypesafeConfigReader.scala:88)
    at scalikejdbc.config.TypesafeConfigReader$$anonfun$readJDBCSettings$2.apply(TypesafeConfigReader.scala:88)
    at scala.Option.getOrElse(Option.scala:120)
    at scalikejdbc.config.TypesafeConfigReader$class.readJDBCSettings(TypesafeConfigReader.scala:87)
    at scalikejdbc.config.DBsWithEnv.readJDBCSettings(DBs.scala:58)
    at scalikejdbc.config.DBs$class.setup(DBs.scala:26)
    at scalikejdbc.config.DBsWithEnv.setup(DBs.scala:58)
    at scalikejdbc.config.DBs$$anonfun$setupAll$1.apply(DBs.scala:34)
    at scalikejdbc.config.DBs$$anonfun$setupAll$1.apply(DBs.scala:34)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scalikejdbc.config.DBs$class.setupAll(DBs.scala:34)
    at scalikejdbc.config.DBsWithEnv.setupAll(DBs.scala:58)
    at org.deepdive.datastore.JdbcDataStore$.init(JdbcDataStore.scala:32)
    at org.deepdive.DeepDive$.run(DeepDive.scala:28)
    at org.deepdive.Main$delayedInit$body.apply(Main.scala:28)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at org.deepdive.Main$.main(Main.scala:10)
    at org.deepdive.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run last compile:run for the full output.

**Comment by dennybritz** [comment]
@feiranwang  Thanks! Something with the directory is wrong:

```
INFO Running pipeline with configuration from /home/feiran/workspace/deepdive/app/./application.conf
```

Are you running from within the `spouse_example` folder?

**Comment by feiranwang** [comment]
@dennybritz Yes, I am running it from deepdive/app/spouse_example folder...

**Comment by dennybritz** [comment]
@feiranwang  Ah I see, found it. In your run.sh, change the APP_HOME to the following line. Will push the fix to that later:

```
export APP_HOME=`pwd`
```

**Comment by feiranwang** [comment]
@dennybritz Oh I see. Thanks!
